@authUrl = {{serverUrl}}/auth
@cityHallsUrl = {{serverUrl}}/city-halls
@authorization = Bearer {{login.response.body.accessToken}}

@email = john@email.com
@password = Pwd@123

# @name login
POST  {{authUrl}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###

@bg_image = #f2f2f2
@email = tangamandapio.ayuntamiento@email.com
@name = Ayuntamiento de Tangamandapio
@phone = 01 (383) 518 32 57
@slug = tangamandapio
@txt_color = #222222

# @name register_city_hall
POST  {{cityHallsUrl}}
Content-Type: application/json
Authorization: {{authorization}}

{
  "bg_image": "{{bg_image}}", 
  "email": "{{email}}", 
  "name": "{{name}}", 
  "phone": "{{phone}}", 
  "slug": "{{slug}}", 
  "txt_color": "{{txt_color}}"
}
###