@authUrl = {{serverUrl}}/auth
@cityHallsUrl = {{serverUrl}}/city-halls


@authorization = Bearer {{auth.response.body.accessToken}}
@userEmail = john@email.com
@userPassword = Pwd@123

# @name auth
POST  {{authUrl}}
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}"
}
###


@bg_image = #f2f2f2
@email = tangamandapio.ayuntamiento@email.com
@name = Ayuntamiento de Tangamandapio
@phone = 01 (383) 518 32 57
@slug = tangamandapio
@txt_color = #222222

# @name register_city_hall
POST  {{cityHallsUrl}}
Content-Type: application/json
Authorization: {{authorization}}

{
  "bg_image": "{{bg_image}}", 
  "email": "{{email}}", 
  "name": "{{name}}", 
  "phone": "{{phone}}", 
  "slug": "{{slug}}", 
  "txt_color": "{{txt_color}}"
}
###

# buscando as prefeituras ativas
# @name list_city_halls
GET  {{cityHallsUrl}}?page=1&perPage=20
###


# buscando as prefeituras deletadas (query param deleted=true)
# @name list_deleted_users
GET  {{cityHallsUrl}}?deleted=true&page=1&perPage=20
###

# buscando uma prefeitura pelo id
# @name list_city_halls
GET  {{cityHallsUrl}}/afac3fa2-6cda-4151-91a5-0a2ea1ec71e2
Authorization: {{authorization}}
###

# buscando uma prefeitura pelo slug
# @name list_city_halls
GET  {{cityHallsUrl}}/slug/tangamandapio
Authorization: {{authorization}}
###