@USERS_URL = {{serverUrl}}/users

@name = John Doe
@email = johndoe@email.com
@password = Pwd@123

# @name create_user
POST  {{USERS_URL}}
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}
###