@authUrl = {{serverUrl}}/auth
@usersUrl = {{serverUrl}}/users

@accessToken = {{authenticate_user.response.body.accessToken}}
@firstUserId = {{list_users.response.body.$.[0].id}}

@name = John Doe
@email = johndoe@email.com
@password = Pwd@123

# @name create_user
POST  {{usersUrl}}
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}
###

# @name authenticate_user
POST  {{authUrl}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###

# @name list_users
GET  {{usersUrl}}
Authorization: Bearer {{accessToken}}
###

# @name show_user
GET  {{usersUrl}}/{{firstUserId}}
Authorization: Bearer {{accessToken}}
###

# @name update_user
# update logged user record
PUT  {{usersUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "{{name}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "currentPassword": "{{password}}"
}
###

# @name update_user_creadentials
# update logged user record
PUT  {{usersUrl}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Updated {{name}}",
  "email": "updated-{{email}}",
  "password": "updated-{{password}}",
  "currentPassword": "{{password}}"
}
###
